namespace Domain.Entities.Enums
{
    public enum TransactionState
    {
        Pending = 1,
        InstructionSent = 2,
        PendingProcessing = 3,
        Processing = 4,
        AwaitingConfirmation = 5,
        Successful = 6,
        Failed = 7,
        Reversed = 8,
        Expired = 9,
        Rejected = 10,
        InsufficientBalance = 11,
        ServiceUnavailable = 12,
        ErrorAmountTooLow = 13,
        ErrorAmountTooHigh = 14,
        WaitingCustomerPayment = 15,
        WaitingCustomerOtpCode = 16,
        WaitingCustomerPaymentAtOperatorSide = 17,
        WaitingCustomerToValidate = 18,
        UnknownError = 19,
        AbonementOrTransactionExpired = 20,
        ErrorCurrencyNotValid = 21,
        ErrorPhoneNumberNotFound = 22,
        ErrorPhoneNumberNotSupported = 23,
        ErrorPhonePrefixNotSupported = 24,
        TransactionCancel = 25,
        ErrorDoublePayment = 26,
        ErrorMomoPayUnAvailable = 27,
        ErrorFloozPayUnAvailable = 28,
        ErrorOmPayUnAvailable = 29,
        DailyMaxNumberTransactionReached = 30,
        DailyMaxAmountTransactionReached = 31,
        MonthlyMaxNumberTransactionReached = 32,
        MonthlyMaxAmountTransactionReached = 33,
        WeeklyMaxAmountTransactionReached = 34,
        WeeklyMaxNumberTransactionReached = 35,
        TransactionProcessedWithError = 36,
        New = 37,
        Processed = 38,
        Validated = 39,
        ApprovalNeeded = 40,
        ApprovalRequested = 41,
        Scheduled = 42,
        Cancelled = 43,
        ProcessingStarted = 44
    }
}